// Guessing game using numbers...
$(document).ready(function() {
	
	
	
	///Player will guess using numbers to match random number generated by system
	
	//players wins by match total of random number
	
	//Create a random number at start of game
	var randNum = Math.floor(Math.random()* 101) +19;
	console.log(randNum);
	
	//Display the random generated number
	$('#randomNum').text(randNum);
	
	//The Intial Values/Totals should be set to 0
	var userScoreTotal = 0;
	var userWins = 0;
	var userLoses = 0;
	var userNumber = 0;
	
	
	//Shows users score, wins and loses
	$('#wins').text(userWins);
	$('#score').text(userScoreTotal);
	$('#loses').text(userLoses);
	
	//Each clicked crystal will add a specific amount to the players total
	//Creates random numbers for each crystal
	var crystal1 = Math.floor(Math.random()* 12) +1;
	var crystal2 = Math.floor(Math.random()* 12) +1;
	var crystal3 = Math.floor(Math.random()* 12) +1;
	var crystal4 = Math.floor(Math.random()* 12) +1;


	//Variable needed for Total Number
	var totalNumber = userNumber;
	
	function win(){
	alert("You win!");
	userWins ++;
	$('#wins').text(userWins);;
	restartGame();
}

	function lose(){
	alert("You lose!");
	userLoses ++;
	$('#loses').text(userLoses);;
	restartGame();
}
	
	function restartGame(){

	var randNum = Math.floor(Math.random() * 101) + 19;
	console.log(randNum);
	var crystal1 = Math.floor(Math.random()* 12) +1;
	var crystal2 = Math.floor(Math.random()* 12) +1;
	var crystal3 = Math.floor(Math.random()* 12) +1;
	var crystal4 = Math.floor(Math.random()* 12) +1;
	var userNumber = 0;	
	$('#randomNum').text(randNum);
	$("#userNum").text(0);
	$("#score").text();

}
			

	
	//Click each crystal to add to total number to equal random
	$('#crystal1').click(function(){
		totalNumber += crystal1;
		$('#userNum').text(totalNumber);
		
		if(totalNumber > randNum){
			lose();
			
		} else if 
			(totalNumber === randNum){
				win();
			}
		});
	
	
	$('#crystal2').click(function(){
		totalNumber += crystal2;
		$('#userNum').text(totalNumber);
		
		if(totalNumber > randNum){
			lose();
			
		} else if 
			(totalNumber === randNum){
				win();
			}
	});
	
	$('#crystal3').click(function(){
		totalNumber += crystal3;
		$('#userNum').text(totalNumber);
		
		if(totalNumber > randNum){
			lose();
			
		} else if 
			(totalNumber === randNum){
				win();
			}

	});
	
	$('#crystal4').click(function(){
		totalNumber += crystal4;
		$('#userNum').text(totalNumber);
		
		if(totalNumber > randNum){
			lose();
			
		} else if 
			(totalNumber === randNum){
				win();
			}

	});
	
	
	
	///Player will guess using numbers to match random number generated by system
	
	
	// random number will be gernerated
	
	//A player will have to guess which cyrstal(4) value can be used to total the random number
	
	//Each clicked crystal will add a specific amount to the players to total
	
	//players wins by match total of random number
	
});